displayName: MeetingAssist
schemaName: contoso_meetMaster
accessControlPolicy: Any
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  settings:
    GenerativeActionsEnabled: true

  isAgentConnectable: true
  gPTSettings:
    defaultSchemaName: contoso_meetMaster.gpt.default

  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: true
    isSemanticSearchEnabled: true
    contentModeration: Medium
    optInUseLatestModels: true

  recognizer:
    kind: GenerativeAIRecognizer

authenticationConfiguration: {}
publishedOn: 2025-07-08T21:50:52.0000000Z
template: default-2.1.0
language: 1033